# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SharkSimFE_CURRENT_FORM.ui'
#
# Created: Mon Dec 07 10:12:40 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(700, 620)
        MainWindow.setMinimumSize(QtCore.QSize(700, 620))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.toolBox = QtGui.QToolBox(self.centralwidget)
        self.toolBox.setFrameShape(QtGui.QFrame.NoFrame)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page_5 = QtGui.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 682, 306))
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.tabWidget = QtGui.QTabWidget(self.page_5)
        self.tabWidget.setGeometry(QtCore.QRect(10, 4, 661, 361))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_35 = QtGui.QLabel(self.tab)
        self.label_35.setGeometry(QtCore.QRect(10, 50, 38, 16))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.comboBox = QtGui.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(50, 50, 591, 20))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 621, 71))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 121, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(130, 30, 451, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.toolButton = QtGui.QToolButton(self.groupBox)
        self.toolButton.setGeometry(QtCore.QRect(590, 30, 25, 19))
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 110, 621, 71))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 121, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(130, 30, 451, 20))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.toolButton_3 = QtGui.QToolButton(self.groupBox_2)
        self.toolButton_3.setGeometry(QtCore.QRect(590, 30, 25, 19))
        self.toolButton_3.setObjectName(_fromUtf8("toolButton_3"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.toolBox.addItem(self.page_5, _fromUtf8(""))
        self.page_6 = QtGui.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 682, 306))
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.groupBox_18 = QtGui.QGroupBox(self.page_6)
        self.groupBox_18.setGeometry(QtCore.QRect(0, 0, 691, 331))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_18.sizePolicy().hasHeightForWidth())
        self.groupBox_18.setSizePolicy(sizePolicy)
        self.groupBox_18.setCheckable(False)
        self.groupBox_18.setObjectName(_fromUtf8("groupBox_18"))
        self.label_36 = QtGui.QLabel(self.groupBox_18)
        self.label_36.setGeometry(QtCore.QRect(20, 20, 46, 13))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.lineEdit_4 = QtGui.QLineEdit(self.groupBox_18)
        self.lineEdit_4.setGeometry(QtCore.QRect(70, 20, 241, 20))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.tabWidget_3 = QtGui.QTabWidget(self.groupBox_18)
        self.tabWidget_3.setGeometry(QtCore.QRect(10, 60, 671, 231))
        self.tabWidget_3.setAutoFillBackground(False)
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.groupBox_19 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_19.setGeometry(QtCore.QRect(320, 20, 331, 151))
        self.groupBox_19.setObjectName(_fromUtf8("groupBox_19"))
        self.comboBox_4 = QtGui.QComboBox(self.groupBox_19)
        self.comboBox_4.setGeometry(QtCore.QRect(109, 33, 181, 20))
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.stackedWidget = QtGui.QStackedWidget(self.groupBox_19)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 60, 291, 80))
        self.stackedWidget.setFrameShape(QtGui.QFrame.Box)
        self.stackedWidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.label = QtGui.QLabel(self.page_3)
        self.label.setGeometry(QtCore.QRect(40, 30, 201, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.stackedWidget.addWidget(self.page_3)
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.layoutWidget = QtGui.QWidget(self.page)
        self.layoutWidget.setGeometry(QtCore.QRect(7, 30, 271, 24))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_39 = QtGui.QLabel(self.layoutWidget)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.horizontalLayout_5.addWidget(self.label_39)
        self.horizontalSlider_27 = QtGui.QSlider(self.layoutWidget)
        self.horizontalSlider_27.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_27.setObjectName(_fromUtf8("horizontalSlider_27"))
        self.horizontalLayout_5.addWidget(self.horizontalSlider_27)
        self.spinBox_23 = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_23.setObjectName(_fromUtf8("spinBox_23"))
        self.horizontalLayout_5.addWidget(self.spinBox_23)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.layoutWidget_2 = QtGui.QWidget(self.page_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(3, 16, 281, 54))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_40 = QtGui.QLabel(self.layoutWidget_2)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.verticalLayout.addWidget(self.label_40)
        self.label_41 = QtGui.QLabel(self.layoutWidget_2)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.verticalLayout.addWidget(self.label_41)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalSlider_28 = QtGui.QSlider(self.layoutWidget_2)
        self.horizontalSlider_28.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_28.setObjectName(_fromUtf8("horizontalSlider_28"))
        self.verticalLayout_2.addWidget(self.horizontalSlider_28)
        self.horizontalSlider_29 = QtGui.QSlider(self.layoutWidget_2)
        self.horizontalSlider_29.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_29.setObjectName(_fromUtf8("horizontalSlider_29"))
        self.verticalLayout_2.addWidget(self.horizontalSlider_29)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.doubleSpinBox_5 = QtGui.QDoubleSpinBox(self.layoutWidget_2)
        self.doubleSpinBox_5.setObjectName(_fromUtf8("doubleSpinBox_5"))
        self.verticalLayout_3.addWidget(self.doubleSpinBox_5)
        self.doubleSpinBox_6 = QtGui.QDoubleSpinBox(self.layoutWidget_2)
        self.doubleSpinBox_6.setObjectName(_fromUtf8("doubleSpinBox_6"))
        self.verticalLayout_3.addWidget(self.doubleSpinBox_6)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.stackedWidget.addWidget(self.page_2)
        self.label_38 = QtGui.QLabel(self.groupBox_19)
        self.label_38.setGeometry(QtCore.QRect(14, 33, 85, 16))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.groupBox_20 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_20.setGeometry(QtCore.QRect(10, 20, 301, 151))
        self.groupBox_20.setObjectName(_fromUtf8("groupBox_20"))
        self.layoutWidget_3 = QtGui.QWidget(self.groupBox_20)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 29, 281, 82))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_28 = QtGui.QVBoxLayout()
        self.verticalLayout_28.setObjectName(_fromUtf8("verticalLayout_28"))
        self.label_42 = QtGui.QLabel(self.layoutWidget_3)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.verticalLayout_28.addWidget(self.label_42)
        self.label_43 = QtGui.QLabel(self.layoutWidget_3)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.verticalLayout_28.addWidget(self.label_43)
        self.label_44 = QtGui.QLabel(self.layoutWidget_3)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.verticalLayout_28.addWidget(self.label_44)
        self.horizontalLayout_4.addLayout(self.verticalLayout_28)
        self.verticalLayout_29 = QtGui.QVBoxLayout()
        self.verticalLayout_29.setObjectName(_fromUtf8("verticalLayout_29"))
        self.horizontalSlider_31 = QtGui.QSlider(self.layoutWidget_3)
        self.horizontalSlider_31.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_31.setObjectName(_fromUtf8("horizontalSlider_31"))
        self.verticalLayout_29.addWidget(self.horizontalSlider_31)
        self.horizontalSlider_32 = QtGui.QSlider(self.layoutWidget_3)
        self.horizontalSlider_32.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_32.setObjectName(_fromUtf8("horizontalSlider_32"))
        self.verticalLayout_29.addWidget(self.horizontalSlider_32)
        self.horizontalSlider_33 = QtGui.QSlider(self.layoutWidget_3)
        self.horizontalSlider_33.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_33.setObjectName(_fromUtf8("horizontalSlider_33"))
        self.verticalLayout_29.addWidget(self.horizontalSlider_33)
        self.horizontalLayout_4.addLayout(self.verticalLayout_29)
        self.verticalLayout_30 = QtGui.QVBoxLayout()
        self.verticalLayout_30.setObjectName(_fromUtf8("verticalLayout_30"))
        self.spinBox_24 = QtGui.QSpinBox(self.layoutWidget_3)
        self.spinBox_24.setObjectName(_fromUtf8("spinBox_24"))
        self.verticalLayout_30.addWidget(self.spinBox_24)
        self.spinBox_25 = QtGui.QSpinBox(self.layoutWidget_3)
        self.spinBox_25.setObjectName(_fromUtf8("spinBox_25"))
        self.verticalLayout_30.addWidget(self.spinBox_25)
        self.spinBox_27 = QtGui.QSpinBox(self.layoutWidget_3)
        self.spinBox_27.setObjectName(_fromUtf8("spinBox_27"))
        self.verticalLayout_30.addWidget(self.spinBox_27)
        self.horizontalLayout_4.addLayout(self.verticalLayout_30)
        self.tabWidget_3.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.groupBox_21 = QtGui.QGroupBox(self.tab_7)
        self.groupBox_21.setGeometry(QtCore.QRect(10, 20, 301, 151))
        self.groupBox_21.setObjectName(_fromUtf8("groupBox_21"))
        self.layoutWidget_4 = QtGui.QWidget(self.groupBox_21)
        self.layoutWidget_4.setGeometry(QtCore.QRect(20, 30, 261, 24))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_45 = QtGui.QLabel(self.layoutWidget_4)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.horizontalLayout_3.addWidget(self.label_45)
        self.horizontalSlider_34 = QtGui.QSlider(self.layoutWidget_4)
        self.horizontalSlider_34.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_34.setObjectName(_fromUtf8("horizontalSlider_34"))
        self.horizontalLayout_3.addWidget(self.horizontalSlider_34)
        self.spinBox_28 = QtGui.QSpinBox(self.layoutWidget_4)
        self.spinBox_28.setObjectName(_fromUtf8("spinBox_28"))
        self.horizontalLayout_3.addWidget(self.spinBox_28)
        self.groupBox_22 = QtGui.QGroupBox(self.tab_7)
        self.groupBox_22.setGeometry(QtCore.QRect(320, 20, 311, 151))
        self.groupBox_22.setObjectName(_fromUtf8("groupBox_22"))
        self.pushButton_6 = QtGui.QPushButton(self.groupBox_22)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 30, 261, 23))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.tabWidget_3.addTab(self.tab_7, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.groupBox_23 = QtGui.QGroupBox(self.tab_8)
        self.groupBox_23.setGeometry(QtCore.QRect(10, 50, 331, 151))
        self.groupBox_23.setObjectName(_fromUtf8("groupBox_23"))
        self.layoutWidget_5 = QtGui.QWidget(self.groupBox_23)
        self.layoutWidget_5.setGeometry(QtCore.QRect(11, 59, 291, 82))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_47 = QtGui.QLabel(self.layoutWidget_5)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.verticalLayout_4.addWidget(self.label_47)
        self.label_48 = QtGui.QLabel(self.layoutWidget_5)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.verticalLayout_4.addWidget(self.label_48)
        self.label_49 = QtGui.QLabel(self.layoutWidget_5)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.verticalLayout_4.addWidget(self.label_49)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_32 = QtGui.QVBoxLayout()
        self.verticalLayout_32.setObjectName(_fromUtf8("verticalLayout_32"))
        self.horizontalSlider_35 = QtGui.QSlider(self.layoutWidget_5)
        self.horizontalSlider_35.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_35.setObjectName(_fromUtf8("horizontalSlider_35"))
        self.verticalLayout_32.addWidget(self.horizontalSlider_35)
        self.horizontalSlider_36 = QtGui.QSlider(self.layoutWidget_5)
        self.horizontalSlider_36.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_36.setObjectName(_fromUtf8("horizontalSlider_36"))
        self.verticalLayout_32.addWidget(self.horizontalSlider_36)
        self.horizontalSlider_37 = QtGui.QSlider(self.layoutWidget_5)
        self.horizontalSlider_37.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_37.setObjectName(_fromUtf8("horizontalSlider_37"))
        self.verticalLayout_32.addWidget(self.horizontalSlider_37)
        self.horizontalLayout_2.addLayout(self.verticalLayout_32)
        self.verticalLayout_33 = QtGui.QVBoxLayout()
        self.verticalLayout_33.setObjectName(_fromUtf8("verticalLayout_33"))
        self.spinBox_29 = QtGui.QSpinBox(self.layoutWidget_5)
        self.spinBox_29.setObjectName(_fromUtf8("spinBox_29"))
        self.verticalLayout_33.addWidget(self.spinBox_29)
        self.doubleSpinBox_7 = QtGui.QDoubleSpinBox(self.layoutWidget_5)
        self.doubleSpinBox_7.setObjectName(_fromUtf8("doubleSpinBox_7"))
        self.verticalLayout_33.addWidget(self.doubleSpinBox_7)
        self.doubleSpinBox_8 = QtGui.QDoubleSpinBox(self.layoutWidget_5)
        self.doubleSpinBox_8.setObjectName(_fromUtf8("doubleSpinBox_8"))
        self.verticalLayout_33.addWidget(self.doubleSpinBox_8)
        self.horizontalLayout_2.addLayout(self.verticalLayout_33)
        self.layoutWidget_6 = QtGui.QWidget(self.groupBox_23)
        self.layoutWidget_6.setGeometry(QtCore.QRect(11, 30, 291, 22))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_46 = QtGui.QLabel(self.layoutWidget_6)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.horizontalLayout_9.addWidget(self.label_46)
        self.comboBox_5 = QtGui.QComboBox(self.layoutWidget_6)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.horizontalLayout_9.addWidget(self.comboBox_5)
        self.groupBox_24 = QtGui.QGroupBox(self.tab_8)
        self.groupBox_24.setGeometry(QtCore.QRect(350, 50, 311, 151))
        self.groupBox_24.setObjectName(_fromUtf8("groupBox_24"))
        self.layoutWidget_7 = QtGui.QWidget(self.groupBox_24)
        self.layoutWidget_7.setGeometry(QtCore.QRect(10, 30, 291, 22))
        self.layoutWidget_7.setObjectName(_fromUtf8("layoutWidget_7"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_50 = QtGui.QLabel(self.layoutWidget_7)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.horizontalLayout_7.addWidget(self.label_50)
        self.comboBox_6 = QtGui.QComboBox(self.layoutWidget_7)
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.horizontalLayout_7.addWidget(self.comboBox_6)
        self.layoutWidget_8 = QtGui.QWidget(self.groupBox_24)
        self.layoutWidget_8.setGeometry(QtCore.QRect(10, 70, 291, 22))
        self.layoutWidget_8.setObjectName(_fromUtf8("layoutWidget_8"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.layoutWidget_8)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_51 = QtGui.QLabel(self.layoutWidget_8)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.horizontalLayout_8.addWidget(self.label_51)
        self.lineEdit_2 = QtGui.QLineEdit(self.layoutWidget_8)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_8.addWidget(self.lineEdit_2)
        self.toolButton_2 = QtGui.QToolButton(self.layoutWidget_8)
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.horizontalLayout_8.addWidget(self.toolButton_2)
        self.layoutWidget_9 = QtGui.QWidget(self.tab_8)
        self.layoutWidget_9.setGeometry(QtCore.QRect(20, 12, 321, 24))
        self.layoutWidget_9.setObjectName(_fromUtf8("layoutWidget_9"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.layoutWidget_9)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_8 = QtGui.QLabel(self.layoutWidget_9)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_10.addWidget(self.label_8)
        self.horizontalSlider_38 = QtGui.QSlider(self.layoutWidget_9)
        self.horizontalSlider_38.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_38.setObjectName(_fromUtf8("horizontalSlider_38"))
        self.horizontalLayout_10.addWidget(self.horizontalSlider_38)
        self.spinBox_30 = QtGui.QSpinBox(self.layoutWidget_9)
        self.spinBox_30.setObjectName(_fromUtf8("spinBox_30"))
        self.horizontalLayout_10.addWidget(self.spinBox_30)
        self.tabWidget_3.addTab(self.tab_8, _fromUtf8(""))
        self.pushButton_7 = QtGui.QPushButton(self.groupBox_18)
        self.pushButton_7.setGeometry(QtCore.QRect(550, 300, 131, 23))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.toolBox.addItem(self.page_6, _fromUtf8(""))
        self.page_7 = QtGui.QWidget()
        self.page_7.setGeometry(QtCore.QRect(0, 0, 682, 306))
        self.page_7.setObjectName(_fromUtf8("page_7"))
        self.groupBox_27 = QtGui.QGroupBox(self.page_7)
        self.groupBox_27.setGeometry(QtCore.QRect(10, 20, 681, 161))
        self.groupBox_27.setObjectName(_fromUtf8("groupBox_27"))
        self.pushButton_8 = QtGui.QPushButton(self.groupBox_27)
        self.pushButton_8.setGeometry(QtCore.QRect(530, 120, 131, 23))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.layoutWidget_40 = QtGui.QWidget(self.groupBox_27)
        self.layoutWidget_40.setGeometry(QtCore.QRect(290, 30, 44, 74))
        self.layoutWidget_40.setObjectName(_fromUtf8("layoutWidget_40"))
        self.verticalLayout_40 = QtGui.QVBoxLayout(self.layoutWidget_40)
        self.verticalLayout_40.setMargin(0)
        self.verticalLayout_40.setObjectName(_fromUtf8("verticalLayout_40"))
        self.spinBox_37 = QtGui.QSpinBox(self.layoutWidget_40)
        self.spinBox_37.setObjectName(_fromUtf8("spinBox_37"))
        self.verticalLayout_40.addWidget(self.spinBox_37)
        self.spinBox_38 = QtGui.QSpinBox(self.layoutWidget_40)
        self.spinBox_38.setObjectName(_fromUtf8("spinBox_38"))
        self.verticalLayout_40.addWidget(self.spinBox_38)
        self.spinBox_39 = QtGui.QSpinBox(self.layoutWidget_40)
        self.spinBox_39.setObjectName(_fromUtf8("spinBox_39"))
        self.verticalLayout_40.addWidget(self.spinBox_39)
        self.layoutWidget_41 = QtGui.QWidget(self.groupBox_27)
        self.layoutWidget_41.setGeometry(QtCore.QRect(190, 30, 86, 80))
        self.layoutWidget_41.setObjectName(_fromUtf8("layoutWidget_41"))
        self.verticalLayout_41 = QtGui.QVBoxLayout(self.layoutWidget_41)
        self.verticalLayout_41.setMargin(0)
        self.verticalLayout_41.setObjectName(_fromUtf8("verticalLayout_41"))
        self.horizontalSlider_45 = QtGui.QSlider(self.layoutWidget_41)
        self.horizontalSlider_45.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_45.setObjectName(_fromUtf8("horizontalSlider_45"))
        self.verticalLayout_41.addWidget(self.horizontalSlider_45)
        self.horizontalSlider_46 = QtGui.QSlider(self.layoutWidget_41)
        self.horizontalSlider_46.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_46.setObjectName(_fromUtf8("horizontalSlider_46"))
        self.verticalLayout_41.addWidget(self.horizontalSlider_46)
        self.horizontalSlider_47 = QtGui.QSlider(self.layoutWidget_41)
        self.horizontalSlider_47.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_47.setObjectName(_fromUtf8("horizontalSlider_47"))
        self.verticalLayout_41.addWidget(self.horizontalSlider_47)
        self.layoutWidget_42 = QtGui.QWidget(self.groupBox_27)
        self.layoutWidget_42.setGeometry(QtCore.QRect(20, 30, 158, 71))
        self.layoutWidget_42.setObjectName(_fromUtf8("layoutWidget_42"))
        self.verticalLayout_42 = QtGui.QVBoxLayout(self.layoutWidget_42)
        self.verticalLayout_42.setMargin(0)
        self.verticalLayout_42.setObjectName(_fromUtf8("verticalLayout_42"))
        self.label_58 = QtGui.QLabel(self.layoutWidget_42)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.verticalLayout_42.addWidget(self.label_58)
        self.label_59 = QtGui.QLabel(self.layoutWidget_42)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.verticalLayout_42.addWidget(self.label_59)
        self.label_60 = QtGui.QLabel(self.layoutWidget_42)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.verticalLayout_42.addWidget(self.label_60)
        self.toolBox.addItem(self.page_7, _fromUtf8(""))
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 682, 306))
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.groupBox_33 = QtGui.QGroupBox(self.page_4)
        self.groupBox_33.setGeometry(QtCore.QRect(70, 2, 681, 321))
        self.groupBox_33.setObjectName(_fromUtf8("groupBox_33"))
        self.frame_3 = QtGui.QFrame(self.groupBox_33)
        self.frame_3.setGeometry(QtCore.QRect(20, 20, 641, 291))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.textBrowser_4 = QtGui.QTextBrowser(self.frame_3)
        self.textBrowser_4.setGeometry(QtCore.QRect(10, 10, 621, 271))
        self.textBrowser_4.setObjectName(_fromUtf8("textBrowser_4"))
        self.toolBox.addItem(self.page_4, _fromUtf8(""))
        self.page_8 = QtGui.QWidget()
        self.page_8.setGeometry(QtCore.QRect(0, 0, 682, 306))
        self.page_8.setObjectName(_fromUtf8("page_8"))
        self.groupBox_28 = QtGui.QGroupBox(self.page_8)
        self.groupBox_28.setGeometry(QtCore.QRect(0, 10, 691, 241))
        self.groupBox_28.setObjectName(_fromUtf8("groupBox_28"))
        self.groupBox_29 = QtGui.QGroupBox(self.groupBox_28)
        self.groupBox_29.setGeometry(QtCore.QRect(20, 30, 301, 151))
        self.groupBox_29.setObjectName(_fromUtf8("groupBox_29"))
        self.layoutWidget_43 = QtGui.QWidget(self.groupBox_29)
        self.layoutWidget_43.setGeometry(QtCore.QRect(10, 30, 107, 81))
        self.layoutWidget_43.setObjectName(_fromUtf8("layoutWidget_43"))
        self.verticalLayout_43 = QtGui.QVBoxLayout(self.layoutWidget_43)
        self.verticalLayout_43.setMargin(0)
        self.verticalLayout_43.setObjectName(_fromUtf8("verticalLayout_43"))
        self.label_61 = QtGui.QLabel(self.layoutWidget_43)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.verticalLayout_43.addWidget(self.label_61)
        self.label_62 = QtGui.QLabel(self.layoutWidget_43)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.verticalLayout_43.addWidget(self.label_62)
        self.label_63 = QtGui.QLabel(self.layoutWidget_43)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.verticalLayout_43.addWidget(self.label_63)
        self.layoutWidget_44 = QtGui.QWidget(self.groupBox_29)
        self.layoutWidget_44.setGeometry(QtCore.QRect(130, 30, 86, 81))
        self.layoutWidget_44.setObjectName(_fromUtf8("layoutWidget_44"))
        self.verticalLayout_44 = QtGui.QVBoxLayout(self.layoutWidget_44)
        self.verticalLayout_44.setMargin(0)
        self.verticalLayout_44.setObjectName(_fromUtf8("verticalLayout_44"))
        self.horizontalSlider_48 = QtGui.QSlider(self.layoutWidget_44)
        self.horizontalSlider_48.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_48.setObjectName(_fromUtf8("horizontalSlider_48"))
        self.verticalLayout_44.addWidget(self.horizontalSlider_48)
        self.horizontalSlider_49 = QtGui.QSlider(self.layoutWidget_44)
        self.horizontalSlider_49.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_49.setObjectName(_fromUtf8("horizontalSlider_49"))
        self.verticalLayout_44.addWidget(self.horizontalSlider_49)
        self.horizontalSlider_50 = QtGui.QSlider(self.layoutWidget_44)
        self.horizontalSlider_50.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_50.setObjectName(_fromUtf8("horizontalSlider_50"))
        self.verticalLayout_44.addWidget(self.horizontalSlider_50)
        self.layoutWidget_45 = QtGui.QWidget(self.groupBox_29)
        self.layoutWidget_45.setGeometry(QtCore.QRect(220, 29, 44, 81))
        self.layoutWidget_45.setObjectName(_fromUtf8("layoutWidget_45"))
        self.verticalLayout_45 = QtGui.QVBoxLayout(self.layoutWidget_45)
        self.verticalLayout_45.setMargin(0)
        self.verticalLayout_45.setObjectName(_fromUtf8("verticalLayout_45"))
        self.spinBox_40 = QtGui.QSpinBox(self.layoutWidget_45)
        self.spinBox_40.setObjectName(_fromUtf8("spinBox_40"))
        self.verticalLayout_45.addWidget(self.spinBox_40)
        self.spinBox_41 = QtGui.QSpinBox(self.layoutWidget_45)
        self.spinBox_41.setObjectName(_fromUtf8("spinBox_41"))
        self.verticalLayout_45.addWidget(self.spinBox_41)
        self.spinBox_42 = QtGui.QSpinBox(self.layoutWidget_45)
        self.spinBox_42.setObjectName(_fromUtf8("spinBox_42"))
        self.verticalLayout_45.addWidget(self.spinBox_42)
        self.groupBox_30 = QtGui.QGroupBox(self.groupBox_28)
        self.groupBox_30.setGeometry(QtCore.QRect(340, 30, 301, 151))
        self.groupBox_30.setObjectName(_fromUtf8("groupBox_30"))
        self.layoutWidget_46 = QtGui.QWidget(self.groupBox_30)
        self.layoutWidget_46.setGeometry(QtCore.QRect(10, 30, 122, 81))
        self.layoutWidget_46.setObjectName(_fromUtf8("layoutWidget_46"))
        self.verticalLayout_46 = QtGui.QVBoxLayout(self.layoutWidget_46)
        self.verticalLayout_46.setMargin(0)
        self.verticalLayout_46.setObjectName(_fromUtf8("verticalLayout_46"))
        self.label_64 = QtGui.QLabel(self.layoutWidget_46)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.verticalLayout_46.addWidget(self.label_64)
        self.label_65 = QtGui.QLabel(self.layoutWidget_46)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.verticalLayout_46.addWidget(self.label_65)
        self.label_66 = QtGui.QLabel(self.layoutWidget_46)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.verticalLayout_46.addWidget(self.label_66)
        self.layoutWidget_47 = QtGui.QWidget(self.groupBox_30)
        self.layoutWidget_47.setGeometry(QtCore.QRect(130, 30, 86, 81))
        self.layoutWidget_47.setObjectName(_fromUtf8("layoutWidget_47"))
        self.verticalLayout_47 = QtGui.QVBoxLayout(self.layoutWidget_47)
        self.verticalLayout_47.setMargin(0)
        self.verticalLayout_47.setObjectName(_fromUtf8("verticalLayout_47"))
        self.horizontalSlider_51 = QtGui.QSlider(self.layoutWidget_47)
        self.horizontalSlider_51.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_51.setObjectName(_fromUtf8("horizontalSlider_51"))
        self.verticalLayout_47.addWidget(self.horizontalSlider_51)
        self.horizontalSlider_52 = QtGui.QSlider(self.layoutWidget_47)
        self.horizontalSlider_52.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_52.setObjectName(_fromUtf8("horizontalSlider_52"))
        self.verticalLayout_47.addWidget(self.horizontalSlider_52)
        self.horizontalSlider_53 = QtGui.QSlider(self.layoutWidget_47)
        self.horizontalSlider_53.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_53.setObjectName(_fromUtf8("horizontalSlider_53"))
        self.verticalLayout_47.addWidget(self.horizontalSlider_53)
        self.layoutWidget_48 = QtGui.QWidget(self.groupBox_30)
        self.layoutWidget_48.setGeometry(QtCore.QRect(220, 29, 44, 81))
        self.layoutWidget_48.setObjectName(_fromUtf8("layoutWidget_48"))
        self.verticalLayout_48 = QtGui.QVBoxLayout(self.layoutWidget_48)
        self.verticalLayout_48.setMargin(0)
        self.verticalLayout_48.setObjectName(_fromUtf8("verticalLayout_48"))
        self.spinBox_43 = QtGui.QSpinBox(self.layoutWidget_48)
        self.spinBox_43.setObjectName(_fromUtf8("spinBox_43"))
        self.verticalLayout_48.addWidget(self.spinBox_43)
        self.spinBox_44 = QtGui.QSpinBox(self.layoutWidget_48)
        self.spinBox_44.setObjectName(_fromUtf8("spinBox_44"))
        self.verticalLayout_48.addWidget(self.spinBox_44)
        self.spinBox_45 = QtGui.QSpinBox(self.layoutWidget_48)
        self.spinBox_45.setObjectName(_fromUtf8("spinBox_45"))
        self.verticalLayout_48.addWidget(self.spinBox_45)
        self.pushButton_9 = QtGui.QPushButton(self.groupBox_28)
        self.pushButton_9.setGeometry(QtCore.QRect(540, 200, 141, 23))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.toolBox.addItem(self.page_8, _fromUtf8(""))
        self.page_9 = QtGui.QWidget()
        self.page_9.setGeometry(QtCore.QRect(0, 0, 682, 306))
        self.page_9.setObjectName(_fromUtf8("page_9"))
        self.groupBox_31 = QtGui.QGroupBox(self.page_9)
        self.groupBox_31.setGeometry(QtCore.QRect(0, 10, 681, 161))
        self.groupBox_31.setObjectName(_fromUtf8("groupBox_31"))
        self.pushButton_10 = QtGui.QPushButton(self.groupBox_31)
        self.pushButton_10.setGeometry(QtCore.QRect(530, 120, 131, 23))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.horizontalSlider_54 = QtGui.QSlider(self.groupBox_31)
        self.horizontalSlider_54.setGeometry(QtCore.QRect(150, 30, 84, 19))
        self.horizontalSlider_54.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_54.setObjectName(_fromUtf8("horizontalSlider_54"))
        self.label_67 = QtGui.QLabel(self.groupBox_31)
        self.label_67.setGeometry(QtCore.QRect(20, 30, 156, 19))
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.spinBox_46 = QtGui.QSpinBox(self.groupBox_31)
        self.spinBox_46.setGeometry(QtCore.QRect(240, 30, 42, 20))
        self.spinBox_46.setObjectName(_fromUtf8("spinBox_46"))
        self.toolBox.addItem(self.page_9, _fromUtf8(""))
        self.page_10 = QtGui.QWidget()
        self.page_10.setGeometry(QtCore.QRect(0, 0, 682, 306))
        self.page_10.setObjectName(_fromUtf8("page_10"))
        self.groupBox_32 = QtGui.QGroupBox(self.page_10)
        self.groupBox_32.setGeometry(QtCore.QRect(10, 10, 681, 291))
        self.groupBox_32.setObjectName(_fromUtf8("groupBox_32"))
        self.frame_2 = QtGui.QFrame(self.groupBox_32)
        self.frame_2.setGeometry(QtCore.QRect(20, 20, 641, 251))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.textBrowser_3 = QtGui.QTextBrowser(self.frame_2)
        self.textBrowser_3.setGeometry(QtCore.QRect(10, 10, 621, 231))
        self.textBrowser_3.setObjectName(_fromUtf8("textBrowser_3"))
        self.toolBox.addItem(self.page_10, _fromUtf8(""))
        self.gridLayout.addWidget(self.toolBox, 1, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.widget = QtGui.QWidget(self.groupBox_3)
        self.widget.setGeometry(QtCore.QRect(20, 24, 641, 24))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.lineEdit_6 = QtGui.QLineEdit(self.widget)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.horizontalLayout.addWidget(self.lineEdit_6)
        self.horizontalLayout_12.addLayout(self.horizontalLayout)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_11.addWidget(self.label_5)
        self.lineEdit_7 = QtGui.QLineEdit(self.widget)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.horizontalLayout_11.addWidget(self.lineEdit_7)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_11)
        self.gridLayout.addWidget(self.groupBox_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.menuSettings.addAction(self.actionPreferences)
        self.menuSettings.addSeparator()
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_35.setText(_translate("MainWindow", "Project:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Project", None))
        self.groupBox.setTitle(_translate("MainWindow", "Application", None))
        self.label_2.setText(_translate("MainWindow", "Application base path:", None))
        self.toolButton.setText(_translate("MainWindow", "...", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Projects", None))
        self.label_3.setText(_translate("MainWindow", "Projects INI file:", None))
        self.toolButton_3.setText(_translate("MainWindow", "...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Settings", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("MainWindow", "Step 1 - Create / select project", None))
        self.groupBox_18.setTitle(_translate("MainWindow", "Scenario", None))
        self.label_36.setText(_translate("MainWindow", "Scenario:", None))
        self.groupBox_19.setTitle(_translate("MainWindow", "Offspring:", None))
        self.label.setText(_translate("MainWindow", "Please specify litter distribution.", None))
        self.label_39.setText(_translate("MainWindow", "Number:", None))
        self.label_40.setText(_translate("MainWindow", "Mean:", None))
        self.label_41.setText(_translate("MainWindow", "Standard Deviation:", None))
        self.label_38.setText(_translate("MainWindow", "Litter distribution:", None))
        self.groupBox_20.setTitle(_translate("MainWindow", "Ageing:", None))
        self.label_42.setText(_translate("MainWindow", "Maximum Age:", None))
        self.label_43.setText(_translate("MainWindow", "Maximum Mating Age:", None))
        self.label_44.setText(_translate("MainWindow", "MinimumMating  Age:", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), _translate("MainWindow", "Life-history", None))
        self.groupBox_21.setTitle(_translate("MainWindow", "GroupBox", None))
        self.label_45.setText(_translate("MainWindow", "Population size:", None))
        self.groupBox_22.setTitle(_translate("MainWindow", "Age cohort survival:", None))
        self.pushButton_6.setText(_translate("MainWindow", "Edit age cohort survival rates", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("MainWindow", "Demography", None))
        self.groupBox_23.setTitle(_translate("MainWindow", "Alleles per locus", None))
        self.label_47.setText(_translate("MainWindow", "Number:", None))
        self.label_48.setText(_translate("MainWindow", "Mean:", None))
        self.label_49.setText(_translate("MainWindow", "Standard Deviation:", None))
        self.label_46.setText(_translate("MainWindow", "Alleles per locus distribution:", None))
        self.groupBox_24.setTitle(_translate("MainWindow", "Allele Frequencies", None))
        self.label_50.setText(_translate("MainWindow", "Allele frequency distribution:", None))
        self.label_51.setText(_translate("MainWindow", "Allele frequency file:", None))
        self.toolButton_2.setText(_translate("MainWindow", "...", None))
        self.label_8.setText(_translate("MainWindow", "Number of Loci:", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow", "Genetics", None))
        self.pushButton_7.setText(_translate("MainWindow", "Save scenario", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6), _translate("MainWindow", "Step 1 - Create / Modify Scenario", None))
        self.groupBox_27.setTitle(_translate("MainWindow", "Run scenario", None))
        self.pushButton_8.setText(_translate("MainWindow", "Run scenario", None))
        self.label_58.setText(_translate("MainWindow", "Burn-in length:", None))
        self.label_59.setText(_translate("MainWindow", "Temporal evolution length:", None))
        self.label_60.setText(_translate("MainWindow", "Number of population replicates:", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_7), _translate("MainWindow", "Step 2 - Run / re-run scenario", None))
        self.groupBox_33.setTitle(_translate("MainWindow", "Sampling strategy results", None))
        self.textBrowser_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/test/AGENE_DEM.png\" /></p></body></html>", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("MainWindow", "Step 3 - Review scenario run", None))
        self.groupBox_28.setTitle(_translate("MainWindow", "Sampling strategy", None))
        self.groupBox_29.setTitle(_translate("MainWindow", "Sample size range", None))
        self.label_61.setText(_translate("MainWindow", "Maximum Samples:", None))
        self.label_62.setText(_translate("MainWindow", "Minimum Samples", None))
        self.label_63.setText(_translate("MainWindow", "Sample size increment", None))
        self.groupBox_30.setTitle(_translate("MainWindow", "Locus number range", None))
        self.label_64.setText(_translate("MainWindow", "Maximum loci:", None))
        self.label_65.setText(_translate("MainWindow", "Minimum loci:", None))
        self.label_66.setText(_translate("MainWindow", "Locus number increment:", None))
        self.pushButton_9.setText(_translate("MainWindow", "Save sampling strategy", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_8), _translate("MainWindow", "Step 4 - Create / modify sampling strategy", None))
        self.groupBox_31.setTitle(_translate("MainWindow", "Run sampling strategy", None))
        self.pushButton_10.setText(_translate("MainWindow", "Run sampling strategy", None))
        self.label_67.setText(_translate("MainWindow", "Number of Ne replicates:", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_9), _translate("MainWindow", "Step 5 - Run / re-run sampling strategy", None))
        self.groupBox_32.setTitle(_translate("MainWindow", "Sampling strategy results", None))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_10), _translate("MainWindow", "Step 6 - Review sampling strategy results", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Current working environment", None))
        self.label_4.setText(_translate("MainWindow", "Current Project:", None))
        self.label_5.setText(_translate("MainWindow", "Current Scenario:", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences", None))

